### ISSUE TITLE
Abort does not work

### ISSUE THREAD

**Issue by MarkPelle** [drigler/viva_wallet_pos#7]
When abort is called, nothing happens. On Viva side, this error occurs:
![a6aaf89e-89f8-47c8-a68d-6607034b84fa](https://github.com/user-attachments/assets/c9c1edcb-e84e-4f0f-8cfd-4e33df8f0023)

`  void abort() async {
    try {
      print("it gets printed");
      AbortResponse response = await _pos.abort();
      print(response.rawData);
      print("response does not get printed...");
    } catch (e) {
      print(e);
      print("error does not get printed.");
    }
  }`

**Comment by drigler** [comment]
What are you traying to abort? Maby there is nothing to be aborted?

For viva exceptions you should post them to  [Viva API devs](https://github.com/VivaPayments)

**Comment by drigler** [comment]
I'm closing this because original OP does not provide feedback and I don't see that the request is really an issue.
